### ISSUE TITLE
asymptote-3.05 does not compile with boost-1.88

### ISSUE THREAD

**Issue by andreygrozin** [vectorgraphics/asymptote#557]
[Gentoo bug](https://bugs.gentoo.org/960289)

```
[ 83%] Building CXX object CMakeFiles/lspcpp.dir/src/lsp/ParentProcessWatcher.cpp.o
/var/tmp/portage/media-gfx/asymptote-3.05/work/asymptote-3.05/LspCpp/src/lsp/ParentProcessWatcher.cpp:25:37: error: opstream is not a member of boost::process
   25 |     std::shared_ptr<boost::process::opstream> write_to_service;
      |                                     ^~~~~~~~
```

In boost-1.88.0, the boost/process v1 api is deprecated.

**Comment by andreygrozin** [comment]
The patch in the Gentoo bug works around the issue. But it would be better to port the code to boost/process v2.

**Comment by johncbowman** [comment]
Commit 0a1e9d68b65891106b042246301e739f2fd65f29 from https://github.com/kuafuwang/LspCpp
doesn't compile, so I updated our fork https://github.com/vectorgraphics/LspCpp to  

```
commit 8d172bd36d22a9faab0119c0faf82fae04c1ab47 (HEAD -> master, origin/master, origin/HEAD)
Merge: d965ebe3 293d498b
Author: kuafuwang <kuafuwang@qq.com>
Date:   Fri May 30 20:20:50 2025 +0800

    Merge pull request #71 from Freed-Wu/address
    
    Support build with boost-1.87.0

```

**Comment by hpreusse** [comment]
Weird. At least the lspcpp I could compile (see attached [make.log](https://github.com/user-attachments/files/21899757/make.log)). The build fails later in a third party module, but this rather looks like a syntax error.
