### ISSUE TITLE
fails to build with latest boost 1.87.0

### ISSUE THREAD

**Issue by david-geiger** [vectorgraphics/asymptote#524]
Hi,

On Mageia Cauldron release 2.98 fails to build with latest boost 1.87.0 with ths following build issue:

> /home/iurt/rpmbuild/BUILD/asymptote-2.98-build/asymptote-2.98/LspCpp/src/jsonrpc/TcpServer.cpp:193:46: error: 'work' is not a member of 'boost::asio::io_context'
  193 |     std::shared_ptr<boost::asio::io_context::work> work;
      |                                              ^~~~
/home/iurt/rpmbuild/BUILD/asymptote-2.98-build/asymptote-2.98/LspCpp/src/jsonrpc/TcpServer.cpp:193:50: error: template argument 1 is invalid
  193 |     std::shared_ptr<boost::asio::io_context::work> work;
      |                                                  ^
/home/iurt/rpmbuild/BUILD/asymptote-2.98-build/asymptote-2.98/LspCpp/src/jsonrpc/TcpServer.cpp: In constructor 'lsp::TcpServer::TcpServer(const std::string&, const std::string&, std::shared_ptr<MessageJsonHandler>, std::shared_ptr<Endpoint>, lsp::Log&, uint32_t)':
/home/iurt/rpmbuild/BUILD/asymptote-2.98-build/asymptote-2.98/LspCpp/src/jsonrpc/TcpServer.cpp:216:61: error: 'work' is not a member of 'boost::asio::io_context'
  216 |     d_ptr->work = std::make_shared<boost::asio::io_context::work>(d_ptr->io_context_);
      |                                                             ^~~~
/home/iurt/rpmbuild/BUILD/asymptote-2.98-build/asymptote-2.98/LspCpp/src/jsonrpc/TcpServer.cpp:216:66: error: no matching function for call to 'make_shared<<expression error> >(boost::asio::io_context&)'
  216 |     d_ptr->work = std::make_shared<boost::asio::io_context::work>(d_ptr->io_context_);
      |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~

Attached full build log:

[build.x86_64.0.20250210145607.log](https://github.com/user-attachments/files/18737545/build.x86_64.0.20250210145607.log)

**Comment by johncbowman** [comment]
Boost seems to cause no end of problems. A workaround for now is to
`./configure --disable-lsp`

**Comment by david-geiger** [comment]
Or using archlinux patch fixes build:

https://gitlab.archlinux.org/archlinux/packaging/packages/asymptote/-/raw/main/boost-1.87.patch?ref_type=heads

**Comment by johncbowman** [comment]
Thanks so much for this patch! It is now applied in commit 7fe989a89945c93c85e1e3cbb3cec4ce7460e170 and will be in today's 2.99 release.
