### ISSUE TITLE
Fails to build on sh4 & m68k since v2.73

### ISSUE THREAD

**Issue by hpreusse** [vectorgraphics/asymptote#295]
Anywhere between 2.70 & 2.73 asymptote stopped building on CPU arch [sh4](https://buildd.debian.org/status/fetch.php?pkg=asymptote&arch=sh4&ver=2.73%2Bds-1&stamp=1640901391&raw=0) & [m68k](https://buildd.debian.org/status/fetch.php?pkg=asymptote&arch=m68k&ver=2.73%2Bds-1&stamp=1640932386&raw=0). The error message is the same on both arches, hence just one issue report:

```
In file included from /usr/include/features.h:472,
                 from /usr/include/m68k-linux-gnu/c++/11/bits/os_defines.h:39,
                 from /usr/include/m68k-linux-gnu/c++/11/bits/c++config.h:586,
                 from /usr/include/c++/11/cassert:43,
                 from util.cc:12:
/usr/include/dirent.h:366:6: error: expected initializer before ‘noexcept’
  366 |      __THROW __nonnull ((2, 4))
      |      ^~~~~~~
```

Please be so kind to have a look at the issue. Thanks!

**Comment by johncbowman** [comment]
It doesn't look like an asymptote issue. Try compiling a short test program containing 
#include <cassert>

It is best to submit bug reports against the latest version, in this case, 2.75. Also try 
./configure --disable-lsp

**Comment by hpreusse** [comment]
Interestingly it works with 2.75 on sh4. I'm waiting for results on m68k [here](https://buildd.debian.org/status/package.php?p=asymptote).
