### ISSUE TITLE
In the 2.39 Makefile, CFLAGS override CXXFLAGS, g++-6.3.0 is not happy with -O3

### ISSUE THREAD

**Issue by zarniwhoop73** [vectorgraphics/asymptote#36]
Just a note that trying to build 2.39 on gcc-6.3.0 without setting any flags, the build fails:
(sorry about the formatting)

g++ -Wall -DHAVE_CONFIG_H -D_FILE_OFFSET_BITS=64 -DUSEGC  -pthread -DFFTWPP_SINGLE_THREAD  -g -O2 -g
-O3 -ansi -fno-var-tracking   -I. -I/opt/texlive/2016/include/gc -I/usr/include/gc -o camperror.o -c
camperror.cc
In file included from /usr/include/c++/6.3.0/unordered_map:35:0,
                 from memory.h:22,
                 from common.h:35,
                 from camperror.h:16,
                 from camperror.cc:14:
/usr/include/c++/6.3.0/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and
library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or
-std=gnu++11 compiler options.

That was a surprise because I had already built and installed it, now I just wanted top get space and time measurements for an out-of-the-box build. My own builds use CFLAGS and CXXFLAGS of  '-g -O2', mostly to save space by omitting debug symbols, plus I've never been keen on general -O3 use going back to when I had much slower hardware.

Changing CXXFLAGS to '-O2' removed the first -g, but the second and the -O3 were still present and the build failed. So the fix to build with gcc-6.3.0 is to export CFLAGS='-g -O2'. Probably won't affect many people.

**Comment by johncbowman** [comment]
For production runs you should definitely compile with -O3. As stated in the documentation:

> To compile without optimization, use the command @code{make CFLAGS=-g}.

We will switch from -ansi to -std=c++11 soon.
