### ISSUE TITLE
asymptote fails to build with libgsl-2.0

### ISSUE THREAD

**Issue by zarniwhoop73** [vectorgraphics/asymptote#3]
gsl.cc: In function ‘void trans::gen_rungsl_venv(trans::venv&)’:
gsl.cc:1091:67: error: no matching function for call to ‘addGSLDOUBLE3Func(sym::symbol&, sym::symbol&, sym::symbol&, sym::symbol&)’
   addGSLDOUBLE3Func<gsl_sf_ellint_D>(SYM(D),SYM(phi),SYM(k),SYM(n));
                                                                   ^
The obvious workaround is to use --disable-gsl, that works fine.+

**Comment by opoplawski** [comment]
We'd like to update Fedora rawhide to gsl 2.1, but we're hitting this.

**Comment by johncbowman** [comment]
Thanks; fixed.

**Comment by opoplawski** [comment]
Verified here, thanks.
